/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcsRouteImport } from './routes/arcs'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as WeaponsRouteImport } from './routes/weapons'
import { Route as ArcsSlugRouteImport } from './routes/arcs.$slug'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as WeaponsSlugRouteImport } from './routes/weapons.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsRoute = ArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsRoute = WeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsSlugRoute = ArcsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArcsRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CharactersRoute,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamsRoute,
} as any)
const WeaponsSlugRoute = WeaponsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WeaponsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/compare': typeof CompareRoute
  '/teams': typeof TeamsRouteWithChildren
  '/weapons': typeof WeaponsRouteWithChildren
  '/arcs/$slug': typeof ArcsSlugRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/weapons/$slug': typeof WeaponsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/compare': typeof CompareRoute
  '/teams': typeof TeamsRouteWithChildren
  '/weapons': typeof WeaponsRouteWithChildren
  '/arcs/$slug': typeof ArcsSlugRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/weapons/$slug': typeof WeaponsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/compare': typeof CompareRoute
  '/teams': typeof TeamsRouteWithChildren
  '/weapons': typeof WeaponsRouteWithChildren
  '/arcs/$slug': typeof ArcsSlugRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/weapons/$slug': typeof WeaponsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcs'
    | '/characters'
    | '/compare'
    | '/teams'
    | '/weapons'
    | '/arcs/$slug'
    | '/characters/$slug'
    | '/teams/$slug'
    | '/weapons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcs'
    | '/characters'
    | '/compare'
    | '/teams'
    | '/weapons'
    | '/arcs/$slug'
    | '/characters/$slug'
    | '/teams/$slug'
    | '/weapons/$slug'
  id:
    | '__root__'
    | '/'
    | '/arcs'
    | '/characters'
    | '/compare'
    | '/teams'
    | '/weapons'
    | '/arcs/$slug'
    | '/characters/$slug'
    | '/teams/$slug'
    | '/weapons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcsRoute: typeof ArcsRouteWithChildren
  CharactersRoute: typeof CharactersRouteWithChildren
  CompareRoute: typeof CompareRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  WeaponsRoute: typeof WeaponsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs': {
      id: '/arcs'
      path: '/arcs'
      fullPath: '/arcs'
      preLoaderRoute: typeof ArcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons': {
      id: '/weapons'
      path: '/weapons'
      fullPath: '/weapons'
      preLoaderRoute: typeof WeaponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs/$slug': {
      id: '/arcs/$slug'
      path: '/$slug'
      fullPath: '/arcs/$slug'
      preLoaderRoute: typeof ArcsSlugRouteImport
      parentRoute: typeof ArcsRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/weapons/$slug': {
      id: '/weapons/$slug'
      path: '/$slug'
      fullPath: '/weapons/$slug'
      preLoaderRoute: typeof WeaponsSlugRouteImport
      parentRoute: typeof WeaponsRoute
    }
  }
}

interface ArcsRouteChildren {
  ArcsSlugRoute: typeof ArcsSlugRoute
}

const ArcsRouteChildren: ArcsRouteChildren = {
  ArcsSlugRoute: ArcsSlugRoute,
}

const ArcsRouteWithChildren = ArcsRoute._addFileChildren(ArcsRouteChildren)

interface CharactersRouteChildren {
  CharactersSlugRoute: typeof CharactersSlugRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersSlugRoute: CharactersSlugRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface TeamsRouteChildren {
  TeamsSlugRoute: typeof TeamsSlugRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsSlugRoute: TeamsSlugRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface WeaponsRouteChildren {
  WeaponsSlugRoute: typeof WeaponsSlugRoute
}

const WeaponsRouteChildren: WeaponsRouteChildren = {
  WeaponsSlugRoute: WeaponsSlugRoute,
}

const WeaponsRouteWithChildren =
  WeaponsRoute._addFileChildren(WeaponsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcsRoute: ArcsRouteWithChildren,
  CharactersRoute: CharactersRouteWithChildren,
  CompareRoute: CompareRoute,
  TeamsRoute: TeamsRouteWithChildren,
  WeaponsRoute: WeaponsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
